version: "3.8"

services:
  payments:
    build:
      context: .
      dockerfile: DockerFile
    container_name: restaurant-payments
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped