services:
  payments:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-payments
    ports:
      - "8000:8000"
    environment:
      - TRANSBANK_COMMERCE_CODE=597055555532
      - TRANSBANK_API_KEY=579B532A7440BB0C9079DED94D31EA161EBE3BBA
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge